### ISSUE TITLE
License

### ISSUE THREAD

**Issue by 3TUSK** [FrogCraft-Rebirth/FrogCraft-Rebirth#1]
The original author didn't add a license into the repo of FrogCraft.
However, he said that he might choose GPL. [Reference](http://forum.industrial-craft.net/index.php?page=Thread&postID=153416#post153416)

On the other hand, M3gaFr3ak did port FrogCraft to 1.6.4 and it accepted by the original author. However there was no license either.

**Comment by 3TUSK** [comment]
Solution 1:

**Comment by liach** [comment]
All MPL or apache suggested.
MPL is stricter than MIT.
GPL is never desirable. Btw you can take a look at eclipse public license.

**Comment by 3TUSK** [comment]
Wait... the *api* will be divide into two parts...

**Comment by liach** [comment]
What two parts?

**Comment by 3TUSK** [comment]
One for mod itself. One for *chemistry*

**Comment by 3TUSK** [comment]
Thus I need to consider about it carefully. The api stuff is still under heavy constructing...

**Comment by liach** [comment]
How do you construct it? So you mean the mod is not open source?

**Comment by 3TUSK** [comment]
I suggest that don't worry about that. *Seems that everything has been mixed together*.

**Comment by 3TUSK** [comment]
@liach Seriously, if you understand that what the purpose this repository actually *has*, you will realize that this issue *is* very hard to solve... question: have you ever played modded minecraft in 1.5.2?

**Comment by liach** [comment]
Nope but vanilla beta. It would be good to choose license later when there's some code

**Comment by 3TUSK** [comment]
Then it's better for us to be quiet. The more talk the more possibilities to be discovered.

**Comment by 3TUSK** [comment]
298a0141c931d6e70b40183f6b91c8a85c433c4d

**Comment by 3TUSK** [comment]
MIT, that's it. Texture will be redone later based on ic2 texture.

**Comment by 3TUSK** [comment]
Actually no one see that the license need to change date.

**Comment by liach** [comment]
You can use some sort of license gradle plugin to automatically apply licenses.

**Comment by 3TUSK** [comment]
Lazy...
