### ISSUE TITLE
Found a typo in readme.md

### ISSUE THREAD

**Issue by panda2134** [FrogCraft-Rebirth/FrogCraft-Rebirth#12]
| Credits　　　　　　　  |   should be "her",i think XD
|　　　　　　　　　　　\/
|Credits to ueyudiud for his generous consultant.
|Credits to dunge for his design idea and several texture.

**Comment by 3TUSK** [comment]
You actually don't know ueyudiud's gender right?

**Comment by 3TUSK** [comment]
Wait, actually it still worth to fix.

**Comment by panda2134** [comment]
XD

2016-01-27 12:29 GMT+08:00 Urey.X. notifications@github.com:

**Comment by panda2134** [comment]
that could be a question. for example, vazkii doesn't like others to use
'he' to refer to her.XD.

2016-01-27 14:39 GMT+08:00 Dao Liu smallpanda2134@gmail.com:

**Comment by 3TUSK** [comment]
Ok this is probably the most weird issue i have ever seen. Will be closed soon or later.
