### ISSUE TITLE
Tiberium logic

### ISSUE THREAD

**Issue by 3TUSK** [FrogCraft-Rebirth/FrogCraft-Rebirth#19]
Anyone who wants know more about tiberium can visit [Wikipedia](https://en.wikipedia.org/wiki/Tiberium) first.

Planned feature:
- [X] Player can be converted into tiberium when killed by tiberium.
- [X] Potion Effect: Tiberium.
- [X] Corrosion. Convert everything into itself.
  - [X] Item.
  - [X] Block.
- [X] Explosion will cause catastrophic consequence 
- [X] ~~Using special sound-wave tool will harvest them effectively.~~ This will be separated into a small addon.

**Comment by Glease** [comment]
Will players be turned into tiberium statue when they die of that PotionEffect?

**Comment by 3TUSK** [comment]
At least there will be some [insert blue/green] crystal left at where they die

**Comment by Glease** [comment]
Well, I was just wondering if you are going to make the world's first Steve Status. (correct me if I was wrong) Anyway, it is still a good idea.

Btw, when you will be free? My ChemLib is approaching its first release. I hope you could have a look at it later. (not now, I haven't yet pushed for a long time and I'm stuck with a werid bug) Integrating it into FC may not be an easy task.

--- Original Message ---

**Comment by 3TUSK** [comment]
I have a 2000+words essay which is due next Monday. Also an easy lab report due this Friday. Also next week is the review week for my Finals. Expect the week of Finals (id est - last week of May this year) - usually that week won't be painful.

**Comment by Glease** [comment]
Well, I'll start being busy when your stuff is done, then.

--- Original Message ---

**Comment by 3TUSK** [comment]
Beside, ChemLab integration will be in another branch, most likely a branch for 1.8. I have kinda of screwed up the integration in 1.7.10 ver.... and also 1.7.10 is fading...

**Comment by Glease** [comment]
Well, I know how nasty those code looks like. You seemingly don't understand how Java APIs locate a implementation without referencing them directly. It's some reflection magic with j.u.ServiceLoader. Anyway, don't worry, you can just focus on the game logic and I'll handle them all. If you are interested how it's done, you could have a look on JAXP FactoryFinder (located in almost every sub-package of package javax.xml).

Btw, Why not directly move on to mc 1.9?

--- Original Message ---

**Comment by 3TUSK** [comment]
Waiting for IC2exp 1.9.

Still a java newer... time to go back and read books.

**Comment by Glease** [comment]
man, what about fluid stuff? I mean, how to handle corrosion on fluid blocks? or does it happen at all?

**Comment by 3TUSK** [comment]
It _does_ happen since it doesn't check what type of block it used to be. 
So it just replace blocks at some random-what-the-hell-why-it-is-in-my-base position(s). No matter it is water or lava or diamond block or Matter Fabricator. (Theoretically)
