### ISSUE TITLE
Ores

### ISSUE THREAD

**Issue by AngelCry** [FrogCraft-Rebirth/FrogCraft-Rebirth#28]
i decided to give this mod a try but soon after start i found i cant even mine any mod ore. they just not harvestable with anything - i tried pickaxe, shovel, just hands and got nothing, ores just do not drop anything. this is intended to be so?

**Comment by 3TUSK** [comment]
I guess I forget to add a proper harvest tool for them.

However... school work is always annoying. I will try to release a new versions in next few days...

**Comment by 3TUSK** [comment]
Just a reminder: you'll gonna need (at least) iron shovel for carnallite, iron pick for dewalquite and fluorapaitite.

**Comment by AngelCry** [comment]
i see you already commit a fix for ores, but are you going to make new build with this (and other) fix any time sone?

**Comment by 3TUSK** [comment]
Still fixing other issues. New version will be released soon (tm)

**Comment by 3TUSK** [comment]
https://github.com/FrogCraft-Rebirth/FrogCraft-Rebirth/releases/tag/0.11.0
