### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by modmuss50** [FrogCraft-Rebirth/FrogCraft-Rebirth#38]
Hi, someone had this crash on the BTM server,

https://pastebin.com/embed_iframe/akkbDNqY

Hopefully you can take a look at it, thanks.

**Comment by 3TUSK** [comment]
Kek, I pushed the fix before I notice this issue - https://github.com/FrogCraft-Rebirth/FrogCraft-Rebirth/commit/2297739763fb5013d704c81d6e4d9fa30999be20

**Comment by 3TUSK** [comment]
https://github.com/FrogCraft-Rebirth/FrogCraft-Rebirth/releases/tag/2.0.4

I have many classes today - sorry for replying late. I believe this build fixes the issue... if there is still a scheduled server update please include this.

**Comment by 3TUSK** [comment]
BTM Moon has started; we can assume that this issue has been fixed. :)
