### ISSUE TITLE
CraftTweaker Support for 1.12?

### ISSUE THREAD

**Issue by Vyraal1** [FrogCraft-Rebirth/FrogCraft-Rebirth#39]
Do you plan on adding CraftTweaker support for FCR? So players can add custom recipes for the various chemical processing machines you have in the mod?

**Comment by 3TUSK** [comment]
It is in the roadmap right now - however, i am personally not sure on making it a standalone mod or just be a part of the mod itself... probably the latter.

**Comment by Pilad** [comment]
Please))

**Comment by 3TUSK** [comment]
@Vyraal1 @Pilad New release with CraftTweaker support will be available at:
https://minecraft.curseforge.com/projects/frogcraft-rebirth/files/2515272
