### ISSUE TITLE
材料未加入矿物词典？

### ISSUE THREAD

**Issue by TechnicianFreak** [FrogCraft-Rebirth/FrogCraft-Rebirth#41]
因为发现与其他mod的铝并不通用，就看了看物品信息发现没矿典那一行。

**Comment by 3TUSK** [comment]
已知问题，几天前在自己的包里发现铝不能被匠魂识别，目前已经在本地修复。

To anyone who wonder what it is:
Aluminium Ingot/Dust/Plate are not registered with OreDict like "ore/dust/plateAluminum" in this mod, making some mods (for example Tinkers Construct) unable to recognize. 
At this moment there has been a config option to enable "Aluminum" series ore dictionary entires. Update incoming.

**Comment by liach** [comment]
应该可以用crafttweaker解决吧

**Comment by 3TUSK** [comment]
https://minecraft.curseforge.com/projects/frogcraft-rebirth/files/2515272
