### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by Trixz2018** [FrogCraft-Rebirth/FrogCraft-Rebirth#43]
minecraft 1.12.2
FrogCraft-Rebirth-2.2.1
industrialcraft-2-2.8.35-ex112
Forge: 14.23.1.2582

Crash Report: https://pastebin.com/37Ft2PHC

I must say i was able to launch with this jar the first time i installed it. While in my SP test world it froze when after placing/breaking certain blocks from your mod. So i killed it and tried to relaunch it and got this crash report.

**Comment by 3TUSK** [comment]
It looks like TechReborn compatibility is enabled somehow... and one of the fluid that it uses hasn't implemented yet.

Try find the option to turn TechReborn compatibility off in the config file.

**Comment by Trixz2018** [comment]
Ok so after changing the config for techreborn compatibility to off i went into a test world to test your mod and after breaking and replacing machines for your mod, my SP world froze and had to kill it.
 Stall Report:  https://pastebin.com/Ldw4AhAa

On relaunch: loaded fine. Went into test world and instant freeze.

Before second relaunch i removed your mod. Loaded fine, went into test world, i was able to break and replace blocks again without game freezing.

further testing will be done.

**Comment by 3TUSK** [comment]
Interesting. I haven't ran into such issue before, but that TATW is the only thing I don't have in my development environment. I know what TATW does, but I have zero knowledge on what it does exactly (in terms of code)... 

I will investigate this game-freezing issue later.

**Comment by Trixz2018** [comment]
So since i have no life, i tested a separate pack with only this mod and ic2 and everything worked. 
I removed tatw from main pack and tested it again, everything worked fine, but ic2 cables were taking a bit to render that they were connected. But that has nothing to do with your mod. It seems that TATW is just buggy with its code, also i have too many mods. I removed it and won't be adding it back in. Btw Happy new year!

**Comment by 3TUSK** [comment]
@Trixz2018 A fixed version will be released soon; reopen this issue if the fix doesn't work.
  

Appendix: the 2.2.2 version can be found here:
https://github.com/FrogCraft-Rebirth/FrogCraft-Rebirth/releases/tag/2.2.2
It will not be on CurseForge; instead, 2.2.3 will (probably) be.

**Comment by Trixz2018** [comment]
i'll test it out, i removed Tatw since then so i prolly wont get the same results but ill report back of issues i have.
