### ISSUE TITLE
[1.12.2] oregen config option

### ISSUE THREAD

**Issue by dancc7t** [FrogCraft-Rebirth/FrogCraft-Rebirth#48]
[EDIT] I am sorry i did not see the EnableOres option in the config. It was all my fault.

Hello, i am making a new modpack for 1.12.2 in which certain ores spawn only in certain biomes but in larger veins,  in order to do this i need the config option to disable the oregen provided by the mod, because cofhworld doesnt override the oregen of each mod. 
FrogCraft is a great mod i want to include in my modpack, it makes a cool synergy with several mods, i would be grateful if you could include an option in the config in the next release.

Thanks.

**Comment by 3TUSK** [comment]
There are many other config options designed for modpack creators, by the way - some of those options might not work (e.g. disable individual machines); they will be functional soon<sup>TM</sup>.
